-- MCP Gateway Database Initialization Script
-- This file initializes the database with sample data for testing

-- Create Organizations
INSERT INTO organizations (name) VALUES
  ('Acme Corporation'),
  ('TechStart Inc'),
  ('Global Enterprises');

-- Create Users
INSERT INTO users (username, organization_id) VALUES
  ('john.doe', 1),
  ('jane.smith', 1),
  ('bob.wilson', 2),
  ('alice.johnson', 3),
  ('charlie.brown', 3);

-- Create MCP Servers
INSERT INTO mcp_servers (name, base_url, organization_id) VALUES
  ('Primary MCP Server', 'http://mcp-1:3000', 1),
  ('Backup MCP Server', 'http://mcp-2:3000', 1),
  ('TechStart MCP', 'http://mcp-ts:3000', 2),
  ('Enterprise MCP', 'http://mcp-enterprise:3000', 3);

-- Create Tool Schemas with sample definitions
INSERT INTO tool_schemas (tool_name, title, description, schema_json, organization_id, enabled) VALUES
  ('translate', 'Translator Tool', 'Translate text between languages',
   '{"title":"Translate","fields":[{"name":"text","type":"textarea","label":"Text to translate"},{"name":"targetLang","type":"text","label":"Target Language"}]}',
   NULL, TRUE),

  ('summarize', 'Summarizer Tool', 'Summarize long text content',
   '{"title":"Summarize","fields":[{"name":"text","type":"textarea","label":"Text to summarize"},{"name":"length","type":"text","label":"Summary length (short/medium/long)"}]}',
   NULL, TRUE),

  ('sentiment', 'Sentiment Analysis', 'Analyze sentiment of text',
   '{"title":"Sentiment Analysis","fields":[{"name":"text","type":"textarea","label":"Text to analyze"}]}',
   NULL, TRUE),

  ('email_classifier', 'Email Classifier', 'Classify emails by category',
   '{"title":"Email Classifier","fields":[{"name":"email_body","type":"textarea","label":"Email content"}]}',
   1, TRUE),

  ('expense_analyzer', 'Expense Analyzer', 'Analyze business expenses',
   '{"title":"Expense Analyzer","fields":[{"name":"amount","type":"text","label":"Amount"},{"name":"category","type":"text","label":"Category"}]}',
   2, TRUE);

-- Sample audit logs (optional)
-- These will be generated by actual tool calls, but you can add test data:
INSERT INTO task_audits (user_id, organization_id, tool_name, status, created_at, execution_time_ms) VALUES
  (1, 1, 'translate', 'SUCCESS', NOW(), 250),
  (1, 1, 'translate', 'SUCCESS', DATE_SUB(NOW(), INTERVAL 5 MINUTE), 180),
  (2, 1, 'summarize', 'SUCCESS', DATE_SUB(NOW(), INTERVAL 10 MINUTE), 350),
  (3, 2, 'sentiment', 'SUCCESS', DATE_SUB(NOW(), INTERVAL 1 HOUR), 200),
  (4, 3, 'email_classifier', 'SUCCESS', DATE_SUB(NOW(), INTERVAL 2 HOUR), 280);

